---
project_name: webapp
app_dir: "/home/{{ ansible_user }}/frontend"
frontend_port: 3000

# ECR settings
ecr_repository: "frontend"
ecr_region: "eu-west-1"
docker_image_tag: "latest"

backend_hosts: "{{ groups['role_backend'] | map('extract', hostvars, 'private_ip') | list }}"
