# Variables for backend servers (private subnet)
ansible_user: ec2-user
ansible_ssh_private_key_file: /path/to/terraform-ansible-webapp-key.pem

# Use load balancer as jump host
ansible_ssh_common_args: >-
  -o ProxyJump=ec2-user@{{ hostvars[groups['role_load_balancer'][0]].ansible_host }} #magic___^_^___line
# Backend application variables
app_dir: "/home/{{ ansible_user }}/backend"
backend_port: 3001

# Database configuration
database_host: "{{ rds_endpoint | default('localhost') }}"
database_port: 5432
database_username: dbadmin
database_password: password
database_name: notesdb

# ECR Docker settings
ecr_repository: "backend-app-repo"
ecr_region: "eu-west-1"
docker_image_tag: "latest"
