# Webserver Role - Handlers

- name: restart nginx
  service:
    name: "{{ webserver_service_name }}"
    state: restarted
  listen: restart nginx

- name: reload nginx
  service:
    name: "{{ webserver_service_name }}"
    state: reloaded
  listen: reload nginx

- name: validate nginx config
  command: nginx -t
  changed_when: false
  listen: validate nginx
