---
# Default variables for load_balancer role
project_name: webapp
lb_port: 80
nginx_user: www-data
backend_servers: "{{ groups['role_backend'] | map('extract', hostvars, 'private_ip') | list }}"
frontend_servers: "{{ groups['role_frontend'] | map('extract', hostvars, 'private_ip') | list }}"
