project_name: webapp
app_dir: "/home/{{ ansible_user }}/backend"
backend_port: 3001
# ECR settings
ecr_repository: "backend"
ecr_region: "eu-west-1"
docker_image_tag: "latest"
# Database config
database_host: localhost
database_port: 5432
database_username: dbadmin
database_password: password
database_name: notesdb