# Variables for backend servers (private subnet)
ansible_user: ubuntu
ansible_ssh_private_key_file: terraform/bastion-key-devops-notes-app.pem

# Use load balancer as jump host
ansible_ssh_common_args: >-
  -o ProxyJump=ec2-user@{{ hostvars[groups['role_load_balancer'][0]].ansible_host }} #magic___^_^___line
# Backend application variables
app_dir: "/home/{{ ansible_user }}/backend"
backend_port: 3001

# Database configuration
database_username: dbadmin
database_password: password
database_name: notesdb

# ECR Docker settings
ecr_repository: "backend-app-repo"
ecr_region: "eu-west-1"
docker_image_tag: "latest"
