# ansible/deploy-fullstack.yml
---
- name: Deploy Load Balancer
  hosts: role_load_balancer
  gather_facts: yes
  become: yes
  roles:
    - role: webserver

- name: Deploy Backend Services
  hosts: role_backend
  gather_facts: yes
  become: yes
  roles:
    - role: backend

- name: Deploy Frontend Services
  hosts: role_frontend
  gather_facts: yes
  become: yes
  roles:
    - role: frontend
